defaults: &defaults
  adapter: sqlite

development:
  database: db/dm_app_development.db
  <<: *defaults

  # Add more repositories
  # repositories:
  #   repo1:
  #     adapter:  postgres
  #     database: sample_development
  #     username: the_user
  #     password: secrets
  #     host:     localhost
  #   repo2:
  #     ...

test:
  database: db/dm_app_test.db
  <<: *defaults
production:
  database: db/dm_app_production.db
  <<: *defaults
