defaults: &defaults
  adapter: mysql2
  username: root
  password:
  socket: /tmp/mysql.sock
  timeout: 5000

development:
  database: ar_dm_perf_development
  <<: *defaults

  # Add more repositories
  # repositories:
  #   repo1:
  #     adapter:  postgres
  #     database: sample_development
  #     username: the_user
  #     password: secrets
  #     host:     localhost
  #   repo2:
  #     ...

test:
  database: ar_dm_perf_test
  <<: *defaults
production:
  database: ar_dm_perf_production
  <<: *defaults
